### PR TITLE
Enabling gofmt checking on our CI

### PR DESCRIPTION
**Pull request by mzylowski**
- added script for running gofmt
- fix gofmt in entire project

Example fail: https://travis-ci.org/mzylowski/kubernetes-entrypoint/jobs/192772946

### CODE REVIEW

**Comment by PiotrProkop** [comment]
Split this to 2 PRs. First is changing CI another one is foxing tests.

**Comment by jjlakis** [comment]
@PiotrProkop Why it can't remain as a single PR?

**Comment by PiotrProkop** [comment]
My bad.

**Comment by PiotrProkop** [comment]
LGTM

**Pull request merged**
