### PR TITLE
Update to use client-go v10.0.0

### PR DESCRIPTION
**Pull request by ian-howell**
This removes dependencies on the stale v1.5.1 client-go and updates
the project to work with the current v10.0.0 release.

This change will make it easier to implement new CRDs which use more
recent versions of client-go

I recognize that there are more than 2000 files changed in this PR. This is due to changes made by godep

### CODE REVIEW

**Comment by ian-howell** [comment]
What're the odds of abandoning go 1.7 in favor of a newer release?

**Comment by ian-howell** [comment]
I've updated the travisCI gates. The gates now check go1.11, go1.11.1, and gotip. The selection of go1.11.1 was pretty arbitrary (it's what I've been using) - it would probably be more prudent to use go1.11.4, since that's what kubernetes 1.13 is using as of [this commit](https://github.com/kubernetes/kubernetes/commit/0faae7d75f181e3f8d8b0e33b03d47374290c85a) (and client-go 10.0.0 [uses kubernetes 1.13](https://github.com/kubernetes/client-go/tree/release-10.0#compatibility-matrix)). I will gladly change it if needed.

**Comment by PiotrProkop** [comment]
Yeah, 1.11.4 sounds good.

**Comment by ian-howell** [comment]
Done. This should be ready to merge :)

**Pull request merged**
